name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  BuildTest:
    name: Build and test JDK ${{ matrix.java_version }}
    runs-on: macOS-latest
    strategy:
      matrix:
        java_version: [11]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java_version }}
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.2
      - name: Build project
        run: ./gradlew assembleDebug
#      - name: gradle check
#        run: ./gradlew check
#      - name: Archive Lint report
#        uses: actions/upload-artifact@v3
#        if: ${{ always() }}
#        with:
#          name: Logcat-Lint-report
#          path: sample/build/reports/lint-results*.html
